baza-trainee/veterano-front

package-lock.json
package.json
src/App.tsx
src/components/ArrowButton.tsx
src/index.css

feature/86/ create ArrowButton component

---

package-lock.json
package.json
src/App.tsx
src/Layout/Layout.tsx
src/components/Header/Header.tsx
src/main.tsx
src/pages/ErrorPage.tsx

feature: added routing and Layout component

---

src/App.tsx
src/components/ArrowButton/ArrowButton.tsx

[https://trello.com/c/8SXYc5kN/102-%D0%B2%D0%B8%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D0%B8-%D1%81%D1%82%D0%B8%D0%BB%D1%96-%D1%96%D0%BA%D0%BE%D0%BD%D0%BE%D0%BA-%D0%B7%D0%B3%D1%96%D0%B4%D0%BD%D0%BE-%D0%BD%D0%BE%D0%B2%D0%BE%D0%BC%D1%83-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83](url)

fix: fix ArrowButtons styles according to new design

---

src/components/Footer/Footer.tsx
src/components/Links/constans/const.ts
src/index.css
tailwind.config.js

поправила баг в компоненті лінк ( при ховері пригав макет) + підправила стилі футера

fix: fix Links hover styles and styling footer

---

src/components/Textarea/Textarea.tsx

feat: added texarea

---

src/Layout/Layout.tsx
src/components/ScrollToTop/ScrollToTop.tsx
src/index.css

вже застововано, можна дивитись вживу

feature: scroll to top done

---

package-lock.json
package.json
src/components/Pagination/Pagination.tsx
src/pages/HomePage.tsx

feature: pagination doone

---

src/components/ArrowButton/ArrowButton.tsx
src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectSection/ProjectSection.tsx

feature: now ProjectCard can get props carousel and search

---

src/components/Switch/Switch.tsx
src/index.css
src/pages/HomePage.tsx
tailwind.config.js

[task](https://trello.com/c/qJgJpdPS/132-switch)

feature: swotch done

---

src/components/Cookies/CookiesPanel.tsx

[ticket](https://trello.com/c/jU0H4bZY/145-%D0%B2%D1%96%D0%B4%D1%86%D0%B5%D0%BD%D1%82%D1%80%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D0%BF%D0%BB%D0%B0%D1%88%D0%BA%D1%83-%D0%BA%D1%83%D0%BA%D1%96%D1%81)

feature: centered cookies panel for screens more 1440

---

src/components/AdminPanel/IconButtons/IconClose.tsx
src/components/AdminPanel/IconButtons/IconPen.tsx

[ticket](https://trello.com/c/bKlmzFPr/136-iconbutton)

feature: icons buttons done

---

src/components/AdminPanel/Input/AdminInput.tsx

[ticket](https://trello.com/c/PNDHpqjh/135-admin-input)

feature: admin input done

---

src/components/Checkbox/Checkbox.tsx
src/components/Input/Input.tsx

fix:input in subscription form

---

src/components/Pagination/Pagination.tsx

[ticket ](https://trello.com/c/jDTyUgVd/183-%D0%B2%D1%96%D0%B4%D1%86%D0%B5%D0%BD%D1%82%D1%80%D1%83%D0%B2%D0%B0-%D1%87%D0%B8%D1%81%D0%BB%D0%B0-%D0%B2-%D0%BF%D0%B0%D0%B3%D1%96%D0%BD%D0%B0%D1%86%D1%96%D1%97)

fix: centred items in pagination

---

public/images/close.svg
src/components/Cookies/CookiesPanel.tsx

[ticket](https://trello.com/c/abSfUpuM/175-%D0%B2%D0%B8%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D0%B8-%D0%BF%D0%BB%D0%B0%D1%88%D0%BA%D1%83-%D0%BA%D1%83%D0%BA%D1%96%D1%81)

fix: added onClick func

---

src/components/SearchForm/SearchForm.tsx
src/index.css

[task](https://trello.com/c/4Ifo5Ba2/178-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-%D0%BF%D1%80%D0%BE%D0%BA%D1%80%D1%83%D1%82%D0%BA%D1%83-%D1%83-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%8F%D1%97)

fix: aadded scroll to category section in HeroSection

---

src/components/Header/Header.tsx
src/pages/ErrorPage.tsx

[ticket](https://trello.com/c/JZKCs3AC/192-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D1%86%D1%96-404-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D1%83)

fix: fix button on 404 page

---

src/components/Pagination/Pagination.tsx

[ticket](https://trello.com/c/f9GgNtAO/188-issue-%D0%BD%D0%B5%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BD%D0%B0-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D1%8C-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BE%D0%BA-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BE%D0%BA-%D0%BF%D1%80%D0%B8-%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D1%96-%D0%BC%D1%96%D0%B6-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B0%D0%BC%D0%B8)

fix: fix pagination

---

src/components/Footer/Footer.tsx

[ticket](https://trello.com/c/UMGYP7uK/190-%D0%B2%D0%B8%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D1%81%D1%8C%D0%BA%D1%96-%D0%BF%D1%80%D0%B0%D0%B2%D0%B0-%D0%B7%D0%B3%D1%96%D0%B4%D0%BD%D0%BE-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D1%83)

fix: fix rights display for screens > 768

---

src/components/Footer/Footer.tsx
src/components/Links/Link.tsx

Виправив всі лінки в футері, потрібно залити на версель щоб перевірити чи відкриваються файли "Політика конфіденційності"  на верселі.

fixed all links in footer

---

src/components/ProjectCard/ProjectCard.tsx
src/pages/SearchResults.tsx

[ticket](https://trello.com/c/aZyMdnB5/191-issue-%D0%BD%D0%B5%D0%BA%D0%BE%D1%80%D0%B5%D0%BA%D1%82%D0%BD%D0%B8%D0%B9-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D1%88%D1%80%D0%B8%D1%84%D1%82%D1%83-%D0%BD%D0%B0-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D1%86%D1%96-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8)

fix: fix font size

---

src/components/SubscribeSection/SubscribeSection.tsx

[ticket](https://trello.com/c/wRGD4jkw/201-issue-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B0-%D0%BD%D0%B0%D0%B4%D1%96%D1%81%D0%BB%D0%B0%D1%82%D0%B8-%D0%B2-%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%BC%D1%83-%D1%81%D1%82%D0%B0%D0%BD%D1%96-%D0%B2-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%96-%D0%BF%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8)

fix: button disabled white no data

---

src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectSection/ProjectSection.tsx

[ticket](https://trello.com/c/mBZgdJTs/203-issue-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D0%B4%D0%B8%D0%B2%D0%B8%D1%82%D0%B8%D1%81%D1%8F-%D0%B2%D1%81%D1%96-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix button text on ProjectSection

---

src/api/SearchAPI.tsx
src/components/PartnersSection/PartnersSection.tsx
src/components/ProjectCard/ProjectCard.tsx

[ticket](https://trello.com/c/3hjqq78L/218-%D0%BF%D1%96%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D0%B8-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8-%D0%B2-%D1%81%D0%B5%D0%BA%D1%86%D1%96%D1%8E-parners)

feature: added images to PartnersSection

---

src/components/SearchForm/SearchForm.tsx

[ticket](https://trello.com/c/ClONmXv9/185-issue-update-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%BF%D0%BE%D0%BB%D1%8F-%D0%BF%D0%BE%D1%88%D1%83%D0%BA%D1%83-%D0%BD%D0%B0-%D0%BF%D0%BB%D0%B0%D0%BD%D1%88%D0%B5%D1%82%D0%BD%D1%96%D0%B9-%D1%82%D0%B0-%D0%BC%D0%BE%D0%B1%D1%96%D0%BB%D1%8C%D0%BD%D1%96%D0%B9-%D0%B2%D0%B5%D1%80%D1%81%D1%96%D1%97-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: change placeholder for mob

---

src/pages/ContactUs/ContactUs.tsx

fixed: changed phone numbes

---

src/api/index.ts

Додав консоль лог для наглядності дебагу

added debug log

---

src/components/ProjectCard/ProjectCard.tsx
src/components/SubscribeSection/SubscribeSection.tsx

[ticket](https://trello.com/c/PTo4LRIL/215-issue-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D0%B2%D0%B2%D0%BE%D0%B4%D1%96-%D0%B2-%D0%BF%D0%BE%D0%BB%D0%B5-email-%D1%81%D0%BF%D0%B5%D1%86%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%96%D0%B2-%D0%B2-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%96-%D0%BF%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8)

fix: validation for email in subscription

---

src/components/SubscribeSection/SubscribeSection.tsx

[ticket](https://trello.com/c/QnU78pKu/236-issue-%D0%BF%D1%80%D0%B8-%D0%B2%D0%B2%D0%BE%D0%B4%D1%96-%D0%BD%D0%B5%D0%BA%D0%BE%D1%80%D0%B5%D0%BA%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D1%83-%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D1%83-email-%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BD%D0%B5-%D0%B2%D0%B8%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%B2-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%96-%D0%BF%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8)

fix: added validation to email (match . after @)

---

src/components/Accordion/Accordion.tsx
src/pages/AboutUs.tsx

[ticket](https://trello.com/c/CiapZFIU/233-issue-weight-%D1%88%D1%80%D0%B8%D1%84%D1%82%D1%83-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D1%83-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B5%D0%B9-%D0%BD%D0%B0-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D1%86%D1%96-%D0%BF%D1%80%D0%BE-%D0%BD%D0%B0%D1%81-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix font-weight

---

src/api/SearchAPI.tsx
src/components/PartnersSection/PartnersSection.tsx

[ticket](https://trello.com/c/IkNtWEHd/235-fix-partners-section-fitching-data)

fix: fix fetching data for partners section

---

src/components/Cookies/CookiesPanel.tsx

[ticket](https://trello.com/c/NbAY1ewp/220-issue-%D0%BF%D0%B0%D0%BD%D0%B5%D0%BB%D1%8C-cookies-%D0%BF%D0%BE%D1%81%D0%B8%D0%BB%D0%B0%D0%BD%D0%BD%D1%8F-%D0%BD%D0%B0-%D0%BF%D0%BE%D0%BB%D1%96%D1%82%D0%B8%D0%BA%D1%83-%D0%BA%D0%BE%D0%BD%D1%84%D1%96%D0%B4%D0%B5%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%BE%D1%81%D1%82%D1%96-%D0%B2%D0%B5%D0%B4%D0%B5-%D0%BD%D0%B0-%D0%BD%D0%B5%D1%96%D1%81%D0%BD%D1%83%D1%8E%D1%87%D0%B8%D0%B9-url-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-404)

fix: added link to privacy policy

---

src/components/CloseBtn/CloseBtn.tsx
src/components/Cookies/CookiesPanel.tsx

[ticket](https://trello.com/c/eRV3xW8Z/219-issue-%D0%BF%D0%B0%D0%BD%D0%B5%D0%BB%D1%8C-cookies-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B0-%D1%85-%D0%BF%D1%80%D0%B8-%D1%85%D0%BE%D0%B2%D0%B5%D1%80%D1%96-%D0%BD%D0%B5-%D0%BF%D1%96%D0%B4%D1%81%D0%B2%D1%96%D1%87%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F)

feature: create component CloseBtn

---

src/components/SubscribeSection/SubscribeSection.tsx

[215](https://trello.com/c/PTo4LRIL/215-issue-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D0%B2%D0%B2%D0%BE%D0%B4%D1%96-%D0%B2-%D0%BF%D0%BE%D0%BB%D0%B5-email-%D1%81%D0%BF%D0%B5%D1%86%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%96%D0%B2-%D0%B2-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%96-%D0%BF%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8)

fix: removed % from match reg

---

src/components/Cookies/CookiesPanel.tsx

Reverts baza-trainee/veterano-front#126

Revert "Fix/242/cookies panel"

---

src/components/Modal/ModalWindow.tsx
src/components/SubscribeSection/SubscribeSection.tsx
src/pages/ContactUs/ContactUsForm.tsx

[239](https://trello.com/c/9fRBNmFK/239-issue-%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D1%80%D0%BE-%D0%BD%D0%B0%D0%B4%D1%96%D1%81%D0%BB%D0%B0%D0%BD%D0%B8%D0%B9-%D0%B7%D0%B2%D0%BE%D1%80%D0%BE%D1%82%D0%BD%D1%96%D0%B9-%D0%B7%D0%B2%D1%8F%D0%B7%D0%BE%D0%BA-%D0%BD%D0%B0-%D0%BF%D0%BB%D0%B0%D0%BD%D1%88%D0%B5%D1%82%D1%96-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%BC%D0%B0%D1%94-%D0%B1%D1%83%D1%82%D0%B8-%D0%B2-%D0%BE%D0%B4%D0%B8%D0%BD-%D1%80%D1%8F%D0%B4%D0%BE%D0%BA)

fix: modal contactus

---

src/components/Footer/Footer.tsx
src/components/Links/Link.tsx
src/components/Links/constans/const.ts
src/index.css

[fisrt](https://trello.com/c/S8mCKpyN/225-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D0%BF%D1%96%D0%B4%D1%82%D1%80%D0%B8%D0%BC%D0%B0%D1%82%D0%B8-%D1%82%D0%B0-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D1%83-%D0%B2-%D1%84%D1%83%D1%82%D0%B5%D1%80%D1%96-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)
[second](https://trello.com/c/Yo8ejlQV/224-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D0%BB%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF%D1%83-%D0%B2-%D1%84%D1%83%D1%82%D0%B5%D1%80%D1%96-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fixed font, button and logo

---

src/components/Hero/Hero.tsx

fix: fix hero url /hero/hero-md.jpeg

---

src/components/SubscribeSection/SubscribeSection.tsx
src/index.css

[250](https://trello.com/c/l8c9M8X0/250-%D0%B2%D0%B8%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D0%B8-%D0%B4%D1%83%D0%B1%D0%BB%D1%8E%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%B2-indexcss)

fix: remove duplicates from index.css

---

src/components/SubscribeSection/SubscribeSection.tsx

[251](https://trello.com/c/jpAmWzM3/251-issue-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D0%B2%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D1%96-%D0%B2-%D0%BF%D0%BE%D0%BB%D0%B5-%D1%96%D0%BC%D1%8F-%D0%B1%D1%96%D0%BB%D1%8C%D1%88%D0%B5-2-%D1%85-%D0%BF%D1%80%D0%BE%D0%B1%D1%96%D0%BB%D1%96%D0%B2-%D0%B2-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%96-%D0%BF%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8)

fix: added validation test for name

---

src/components/Input/Input.tsx
src/index.css

[252](https://trello.com/c/c6rmYEB1/252-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D1%88%D1%80%D0%B8%D1%84%D1%82%D0%B0-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D1%83-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%83-%D0%BF%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fixed styling

---

src/components/Cookies/CookiesPanel.tsx

[257](https://trello.com/c/Z93ORcv2/257-%D0%BF%D0%B5%D1%80%D0%B5%D1%80%D0%BE%D0%B1%D0%B8%D1%82%D0%B8-%D0%BA%D1%83%D0%BA%D1%96-%D0%BF%D0%B0%D0%BD%D0%B5%D0%BB%D1%8C-%D0%B7%D0%B3%D1%96%D0%B4%D0%BD%D0%BE-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: new tab view of cookies panel

---

src/components/Cookies/CookiesPanel.tsx

[242](https://trello.com/c/AHuKjtj0/242-issue-%D0%BF%D0%B0%D0%BD%D0%B5%D0%BB%D1%8C-cookies-%D0%BD%D0%B5%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D1%88%D1%80%D0%B8%D1%84%D1%82%D1%96%D0%B2-%D1%82%D0%B0-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80%D1%96%D0%B2)

fix: fix fonts and size according to 242

---

src/components/DropDown/DropDown.tsx
src/components/FilterButton/FilterButton.tsx
src/components/SearchBar/SearchBar.tsx
src/components/SearchForm/SearchForm.tsx
src/index.css

[223](https://trello.com/c/TygsnTQ5/223-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D1%88%D1%80%D0%B8%D1%84%D1%82%D1%83-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0-%D1%84%D1%96%D0%BB%D1%8C%D1%82%D1%80%D1%83-%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0-%D0%BC%D1%96%D1%81%D1%82%D0%BE-weight-400-%D0%B7%D0%B0%D0%BC%D1%96%D1%81%D1%82%D1%8C-300-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BE)

fix: changed width fot tablet, fix font sizes, weight and color

---

src/index.css

fixed index

---

src/components/Cookies/CookiesPanel.tsx

[242](https://trello.com/c/AHuKjtj0/242-issue-%D0%BF%D0%B0%D0%BD%D0%B5%D0%BB%D1%8C-cookies-%D0%BD%D0%B5%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D1%88%D1%80%D0%B8%D1%84%D1%82%D1%96%D0%B2-%D1%82%D0%B0-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80%D1%96%D0%B2)

fix: fix cookies

---

src/pages/ErrorPage.tsx

[264](https://trello.com/c/OkNNGZZN/264-issue-%D1%88%D1%80%D0%B8%D1%84%D1%82-%D0%B5%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%96%D0%B2-404-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D0%B8-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix 404 fonts

---

src/components/Header/Sidebar.tsx

[273](https://trello.com/c/wimrhB0l/273-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D0%B1%D1%83%D1%80%D0%B3%D0%B5%D1%80-%D0%BC%D0%B5%D0%BD%D1%8E-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix birger menu width

---

src/components/Header/Header.tsx

[274](https://trello.com/c/sAkBswRE/274-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D0%BF%D1%96%D0%B4%D1%82%D1%80%D0%B8%D0%BC%D0%B0%D1%82%D0%B8-%D0%B2-%D1%85%D0%B5%D0%B4%D0%B5%D1%80%D1%96-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix button width and height

---

src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectSection/ProjectSection.tsx

[263](https://trello.com/c/MVUQ5yiA/263-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D0%B4%D0%B5%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%96%D1%88%D0%B5-%D0%B2-%D0%B1%D0%BB%D0%BE%D1%86%D1%96-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BD%D0%B0-%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D1%96%D0%B9-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D1%86%D1%96-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix btn style

---

src/components/DropDown/DropDown.tsx
src/components/Hero/Hero.tsx
src/components/SearchBar/SearchBar.tsx

[266](https://trello.com/c/gmG6y5Zu/266-issue-hero-%D0%BD%D0%B5%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix text width

---

src/pages/SearchResults.tsx

[280](https://trello.com/c/OLj5dOxs/280-issue-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%B2-%D0%BA%D0%B0%D1%80%D1%82%D1%86%D1%96-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D1%83-%D0%BD%D0%B0-%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D1%96%D0%B9-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D1%86%D1%96-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D1%83-%D0%B2-%D0%BA%D0%B0%D1%80%D1%82%D1%86%D1%96-%D0%BD%D0%B0-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D1%86%D1%96-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BF%D0%BE%D1%88%D1%83%D0%BA)

fix: fix description appearance

---

src/components/DropDown/DropDown.tsx
src/components/SearchBar/SearchBar.tsx
src/components/SearchForm/SearchForm.tsx
src/index.css
src/pages/SearchResults.tsx

[278](https://trello.com/c/7wxGnIvZ/278-issue-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B0-%D0%BF%D1%96%D0%B4%D1%82%D1%80%D0%B8%D0%BC%D0%B0%D1%82%D0%B8-%D0%B2-%D0%B1%D1%83%D1%80%D0%B3%D0%B5%D1%80-%D0%BC%D0%B5%D0%BD%D1%8E-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix issues with dropdown list opening

---

src/components/Header/Sidebar.tsx

[282](https://trello.com/c/mON4347e/282-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D1%87%D0%B5%D0%BA-%D0%B1%D0%BE%D0%BA%D1%81%D1%83-%D0%B2-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%96-%D0%BF%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B8-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83-%D0%B2-%D0%BC%D0%BE%D0%B1%D1%96%D0%BB%D1%8C%D0%BD%D1%96%D0%B9-%D0%B2%D0%B5%D1%80%D1%81%D1%96%D1%97)

fix: fix support btn

---

src/pages/login/LoginForm.tsx

hotfix: hide error panel

---

src/components/AdminPanel/DropwDown/CategoryDropDown.tsx
src/components/AdminPanel/DropwDown/CitiesDropDown.tsx
src/components/AdminPanel/HeaderComponent.tsx
src/components/AdminPanel/Input/AdminInput.tsx
src/components/AdminPanel/ListElements/ListElement.tsx
src/components/AdminPanel/ListElements/TableHeader.tsx
src/components/AdminPanel/Projects/ProjectsForm.tsx
src/components/AdminPanel/PublishComponent.tsx
src/index.css

[287](https://trello.com/c/PEB3PSUs/287-issue-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D1%84%D1%96%D0%BB%D1%8C%D1%82%D1%80%D1%83-%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0-%D0%BC%D1%96%D1%81%D1%82%D0%BE-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix admin page styling

---

src/pages/login/LoginForm.tsx

[286](https://trello.com/c/wzXti8tB/286-issue-%D0%BF%D1%80%D0%B8-%D0%B2%D0%B2%D0%BE%D0%B4%D1%96-%D0%BD%D0%B5%D0%BA%D0%BE%D1%80%D0%B5%D0%BA%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D1%83-%D0%B4%D0%B0%D0%BD%D0%B8%D1%85-%D0%B2-%D0%B2%D1%96%D0%BA%D0%BD%D1%96-%D0%B2%D1%85%D0%BE%D0%B4%D1%83-%D0%B2-%D0%B0%D0%B4%D0%BC%D1%96%D0%BD%D0%BA%D1%83-%D0%BD%D0%B5-%D0%B2%D0%B8%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D1%8C%D1%81%D1%8F-%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D1%80%D0%BE-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D1%83)

fix: add validation to email auth

---

src/components/PartnersCard/PartnersCard.tsx

[285](https://trello.com/c/WBUFlAdY/285-issue-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8-%D0%BB%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF%D1%83-%D0%B2-%D0%B1%D0%BB%D0%BE%D1%86%D1%96-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D0%B8-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix img size for partners

---

src/pages/admin/PartnersPage/PartnersPage.tsx
src/pages/admin/ProjectsPage/ProjectsPage.tsx

[302](https://trello.com/c/wUlINwiQ/302-issue-admin-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D0%BF%D0%BE%D1%88%D1%83%D0%BA%D1%83)

fix: fix search on partner and projects page

---

src/components/AdminPanel/DropwDown/CategoryDropDown.tsx
src/components/AdminPanel/DropwDown/CitiesDropDown.tsx
src/components/AdminPanel/Input/AdminInput.tsx
src/components/AdminPanel/PartnerForm/PartnerForm.tsx
src/components/AdminPanel/Projects/ProjectsForm.tsx
src/pages/admin/ProjectsPage/EditProjectPage.tsx
src/pages/admin/ProjectsPage/validationShema.ts

[300](https://trello.com/c/Aktj9vSP/300-issue-admin-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D0%B8-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D0%B4%D0%BE%D0%B4%D0%B0%D0%B2%D0%B0%D0%BD%D0%BD%D1%96-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D0%B0)

fix: fix partners and projects

---

src/Layout/AdminLayout.tsx

[309](https://trello.com/c/xKRtT4Hf/309-issue-admin-%D0%BF%D1%80%D0%B8-%D0%BD%D0%B0%D1%82%D0%B8%D1%81%D0%BA%D0%B0%D0%BD%D0%BD%D1%96-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D0%B2%D0%B8%D1%85%D1%96%D0%B4-%D1%83-%D0%B0%D0%B4%D0%BC%D1%96%D0%BD-%D0%BF%D0%B0%D0%BD%D0%B5%D0%BB%D1%96-%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D1%82%D1%83%D0%B2%D0%B0%D1%87-%D0%BD%D0%B5-%D0%B2%D0%B8%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F)

fix: logout admin

---

src/components/AdminPanel/PartnerForm/PartnerForm.tsx
src/components/AdminPanel/Projects/ProjectsForm.tsx
src/pages/admin/ProjectsPage/validationShema.ts
src/validationFields/validationFields.ts

[315](https://trello.com/c/bTE3BOfM/315-issue-admin-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D1%80%D0%B5%D0%B4%D1%96%D1%80%D0%B5%D0%BA%D1%82%D1%96-%D0%BD%D0%B0-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D1%83-%D0%B7-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%BE%D0%BC)

fix: fix url field

---

src/components/AdminPanel/DropwDown/CitiesDropDown.tsx
src/components/AdminPanel/Projects/ProjectsForm.tsx

[316](https://trello.com/c/sjznGS2H/316-issue-admin-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BD%D0%B5-%D0%B2%D1%96%D1%80%D0%BD%D0%BE-%D0%B7%D0%B1%D0%B5%D1%80%D1%96%D0%B3%D0%B0%D1%8E%D1%82%D1%8C%D1%81%D1%8F-%D0%B4%D0%B0%D0%BD%D1%96-%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0-%D0%BC%D1%96%D1%81%D1%82%D0%BE)

fix: fix Country/City order

---

src/components/SearchForm/SearchForm.tsx
src/index.css

[266](https://trello.com/c/gmG6y5Zu/266-issue-hero-%D0%BD%D0%B5%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix scroll on mozilla

---

src/hooks/useContacts.ts

[320](https://trello.com/c/Dcv1v5hY/320-get-https-requiest-is-sending-continuously-1-sec-api-v1-search-all-contactseach)

fix: fix https requiest is sending continuously

---

src/components/ImageCroper/FileDrop.tsx
src/components/ProjectCard/ProjectCard.tsx
src/validationFields/validationFields.ts

[313](https://trello.com/c/HAq615ps/313-admin-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D1%82%D0%B0-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D0%B8-%D0%B4%D0%BE%D0%B7%D0%B2%D0%BE%D0%BB%D1%8F%D1%94-%D0%BE%D0%B1%D0%B8%D1%80%D0%B0%D1%82%D0%B8-%D1%84%D0%B0%D0%B9%D0%BB%D0%B8-%D0%BD%D0%B5%D0%B2%D0%B0%D0%BB%D1%96%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D1%83)

fix: added accepted files to DropZOne

---

src/components/DropDown/DropDown.tsx

[333](https://trello.com/c/KZEIGjzp/333-issue-hero-search-%D0%BD%D0%B5%D0%BC%D0%B0%D1%94-%D0%BC%D0%BE%D0%B6%D0%BB%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D1%96-%D0%BF%D0%BE%D0%B4%D0%B8%D0%B2%D0%B8%D1%82%D0%B8%D1%81%D1%8C-%D0%B2%D1%81%D1%96-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BF%D1%96%D1%81%D0%BB%D1%8F-%D0%BF%D0%BE%D1%88%D1%83%D0%BA%D1%83-%D0%BF%D0%BE-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%96%D0%B7%D0%B0%D1%86%D1%96%D1%97)

fix: added all locations to the list in country filter

---

src/pages/admin/PartnersPage/PartnersPage.tsx
src/pages/admin/ProjectsPage/ProjectsPage.tsx

[346](https://trello.com/c/IDAG5UgW/346-issue-%D0%B0%D0%B4%D0%BC%D1%96%D0%BD-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D1%82%D0%B0-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D0%B8%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%B2%D1%96%D0%B4%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BE%D0%BA-%D0%B3%D0%BE%D1%80%D1%82%D0%B0%D0%BD%D0%BD%D1%8F)

fix: hiding pagination when no results

---

src/components/DropDown/DropDown.tsx

fix list displaying when no data

hotfix: fix list displaying when no data

---

src/components/AdminPanel/PartnerForm/PartnerForm.tsx
src/components/AdminPanel/Projects/ProjectsForm.tsx
src/components/ImageCroper/FileDrop.tsx

дотично до [330](https://trello.com/c/8ZJRZfD4/330-issue-%D0%B0%D0%B4%D0%BC%D1%96%D0%BD-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BF%D1%80%D0%B8-%D0%B4%D0%BE%D0%B4%D0%B0%D0%B2%D0%B0%D0%BD%D0%BD%D1%96-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D1%83-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-errfailed-413-request-entity-too-large-%D0%B6%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D1%82%D1%83)

Hotfix/no ref/validation for image size

---

src/pages/SearchResults.tsx

[340](https://trello.com/c/5wG3nM3C/340-issue-%D0%BA%D0%BE%D0%BF%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B8-%D1%89%D0%B5-%D0%B2-%D0%BC%D0%BE%D0%B1%D1%96%D0%BB%D1%8C%D0%BD%D1%96%D0%B9-%D0%B2%D0%B5%D1%80%D1%81%D1%96%D1%97-%D0%BD%D0%B5%D0%BA%D0%BE%D1%80%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BF%D1%80%D0%B0%D1%86%D1%8E%D1%94)

fix: hide load more  button if no more results

---

src/components/Carousel/Carousel.tsx
src/components/PartnersCard/PartnersCard.tsx

[345](https://trello.com/c/gVpinVGW/345-issue-tool-tip-for-partner-not-displaying)

fix: added tooltip rof partners in carousel

---

src/pages/admin/ProjectsPage/ProjectsPage.tsx
src/pages/adminPage/contacts/schema.ts

[348](https://trello.com/c/HcZjanUh/348-admin-contacts-fix-validation-message)

fix: fix error message

---

src/api/types/SearchTypes.ts
utils/backDataToProjectCardProps.ts

hotfix: fix redirect url for projects

---

src/components/Carousel/Carousel.tsx
src/components/ProjectSection/ProjectSection.tsx

[350](https://trello.com/c/CX1QU2XL/350-issue-%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%B2%D1%96%D0%B4%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-%D0%B1%D0%BB%D0%BE%D0%BA%D1%83-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8-%D0%BD%D0%B0-%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D1%96%D0%B9-%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D1%86%D1%96)

fix: fix width projects card in carousel

---

src/components/DropDown/DropDown.tsx
src/index.css

[353](https://trello.com/c/5kakbeSt/353-issue-%D0%BF%D0%BE%D0%BB%D0%B5-%D1%84%D1%96%D0%BB%D1%8C%D1%82%D1%80%D1%83-%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0-%D0%BC%D1%96%D1%81%D1%82%D0%BE-%D0%BD%D0%B5-%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D1%94-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D1%83)

fix: fix backround on autoComplete

---

src/api/CardsApi.ts
src/components/AdminPanel/DropwDown/CategoryDropDown.tsx

[354](https://trello.com/c/1G0YQOB8/354-issue-%D0%B0%D0%B4%D0%BC%D1%96%D0%BD-%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D0%B8%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D0%B2%D0%B8%D0%B2%D0%BE%D0%B4%D1%96-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D1%83-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D0%B9-%D0%B2-%D0%B2%D1%96%D0%BA%D0%BD%D1%96-%D1%80%D0%B5%D0%B4%D0%B0%D0%B3%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)

fix: new endpont for admin categories

---

package-lock.json
package.json
src/Layout/AdminLayout.tsx
src/api/CardsApi.ts
src/api/PartnersAPI.ts
src/pages/admin/PartnersPage/PartnersPage.tsx
src/pages/login/LoginForm.tsx

add auth headers for adding cards and partners

hotfix: add auth headers for adding cards and partners
